import { describe, it, expect } from "vitest";
import {
  buildSettlementKeyInput,
  deterministicSettlementKey,
} from "./deterministicKey";
import type { SettlementKeyParts } from "./deterministicKey";

const BASE: SettlementKeyParts = {
  siteId: "site-123",
  recordIds: ["rec-a", "rec-b", "rec-c"],
  amount: 800,
  paymentChannel: "engineer_wallet",
  date: "2026-06-11",
};

// ---------------------------------------------------------------------------
// buildSettlementKeyInput
// ---------------------------------------------------------------------------

describe("buildSettlementKeyInput", () => {
  it("starts with v1|", () => {
    expect(buildSettlementKeyInput(BASE)).toMatch(/^v1\|/);
  });

  it("permuting recordIds order yields the SAME string", () => {
    const a = buildSettlementKeyInput({ ...BASE, recordIds: ["rec-a", "rec-b", "rec-c"] });
    const b = buildSettlementKeyInput({ ...BASE, recordIds: ["rec-c", "rec-a", "rec-b"] });
    const c = buildSettlementKeyInput({ ...BASE, recordIds: ["rec-b", "rec-c", "rec-a"] });
    expect(a).toBe(b);
    expect(b).toBe(c);
  });

  it("changing amount yields a DIFFERENT string", () => {
    const a = buildSettlementKeyInput({ ...BASE, amount: 800 });
    const b = buildSettlementKeyInput({ ...BASE, amount: 900 });
    expect(a).not.toBe(b);
  });

  it("800 and 800.00 normalize to the same string (same paise)", () => {
    const a = buildSettlementKeyInput({ ...BASE, amount: 800 });
    const b = buildSettlementKeyInput({ ...BASE, amount: 800.00 });
    expect(a).toBe(b);
  });

  it("800.005 rounds to same paise as 800.00 (Math.round)", () => {
    // 800.005 * 100 = 80000.5 → Math.round → 80001, different from 80000
    const a = buildSettlementKeyInput({ ...BASE, amount: 800 });
    const b = buildSettlementKeyInput({ ...BASE, amount: 800.001 });
    // 800.001 * 100 = 80000.1 → rounds to 80000 → same
    expect(a).toBe(b);
  });

  it("changing paymentChannel changes the string", () => {
    const a = buildSettlementKeyInput({ ...BASE, paymentChannel: "engineer_wallet" });
    const b = buildSettlementKeyInput({ ...BASE, paymentChannel: "direct" });
    expect(a).not.toBe(b);
  });

  it("changing date changes the string", () => {
    const a = buildSettlementKeyInput({ ...BASE, date: "2026-06-11" });
    const b = buildSettlementKeyInput({ ...BASE, date: "2026-06-12" });
    expect(a).not.toBe(b);
  });

  it("changing siteId changes the string", () => {
    const a = buildSettlementKeyInput({ ...BASE, siteId: "site-123" });
    const b = buildSettlementKeyInput({ ...BASE, siteId: "site-456" });
    expect(a).not.toBe(b);
  });

  it("changing extra changes the string", () => {
    const a = buildSettlementKeyInput({ ...BASE, extra: undefined });
    const b = buildSettlementKeyInput({ ...BASE, extra: "laborer-99:2026-06" });
    expect(a).not.toBe(b);
  });

  it("including extra vs omitting extra produces different strings", () => {
    const noExtra = buildSettlementKeyInput({ ...BASE });
    const withExtra = buildSettlementKeyInput({ ...BASE, extra: "x" });
    expect(noExtra).not.toBe(withExtra);
  });
});

// ---------------------------------------------------------------------------
// deterministicSettlementKey
// ---------------------------------------------------------------------------

describe("deterministicSettlementKey", () => {
  it("returns a string matching the UUID v5 regex", async () => {
    const uuid = await deterministicSettlementKey(BASE);
    expect(uuid).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
    );
  });

  it("same input → same UUID on repeated calls", async () => {
    const first = await deterministicSettlementKey(BASE);
    const second = await deterministicSettlementKey(BASE);
    expect(first).toBe(second);
  });

  it("permuted recordIds → same UUID", async () => {
    const a = await deterministicSettlementKey({ ...BASE, recordIds: ["rec-a", "rec-b", "rec-c"] });
    const b = await deterministicSettlementKey({ ...BASE, recordIds: ["rec-c", "rec-a", "rec-b"] });
    expect(a).toBe(b);
  });

  it("different amount → different UUID", async () => {
    const a = await deterministicSettlementKey({ ...BASE, amount: 800 });
    const b = await deterministicSettlementKey({ ...BASE, amount: 801 });
    expect(a).not.toBe(b);
  });

  it("snapshot: stable known-input → known output (algorithm regression guard)", async () => {
    const input: SettlementKeyParts = {
      siteId: "site-snapshot",
      recordIds: ["id-1", "id-2"],
      amount: 1500,
      paymentChannel: "engineer_wallet",
      date: "2026-01-01",
      extra: "laborer-42:2026-01",
    };
    const uuid = await deterministicSettlementKey(input);
    // This snapshot was generated by the implementation on first run.
    // If this test fails after a refactor, the algorithm changed — DO NOT
    // update the snapshot without reviewing the impact on prod idempotency keys.
    expect(uuid).toBe("ba290d19-976d-5f28-bb3a-c1aaf13feea5");
  });
});
