-- ============================================================
-- Granite/marble slab lines on request + purchase-order items
--
-- Area materials (unit = sqft/sqm) are bought by SLAB DIMENSIONS, not
-- by a bare number. A site asks for specific finished pieces
-- ("KitchenTop: 10' x 2' 6" x4" = 100 sq.ft); the vendor never stocks
-- those exact sizes, so the company buys slightly bigger/smaller slabs
-- and cuts/joins them on site. The vendor is paid on what was ACTUALLY
-- bought, per sq.ft.
--
-- This stores both sides of that story:
--   material_request_items.granite_lines -> what the site asked for
--   purchase_order_items.granite_lines   -> what was actually bought
--
-- Invariants:
--   * The two are INDEPENDENT and neither overwrites the other. The
--     gap between them IS the offcut/wastage and must stay visible —
--     it is the number that tells you whether the slabs were bought
--     smartly. Do not "reconcile" one into the other.
--   * Computed sq.ft is NEVER stored twice — requested_qty / quantity
--     remain the numeric truth, derived client-side by graniteSqft()
--     from these dimensions (same rule as spaces.granite_lines). A
--     corrected dimension must recompute the area, never disagree with it.
--   * Same JSONB shape as spaces.granite_lines, and JSONB for the same
--     reason: always read/written with its parent item row, never
--     queried independently. Hence no index, no CHECK.
--   * Actual slabs are captured at the PO ONLY. A delivery just receives
--     the PO quantity; it does not re-open the sizes.
--   * Inert for every non-area material: the default '[]' is simply
--     never populated unless materials.unit is sqft/sqm (isAreaUnit()).
--
-- Additive and backward compatible: existing rows get '[]' and every
-- current reader is unaffected. Pre-existing granite rows kept their
-- sizes only as a flattened string in notes (the structured lines were
-- discarded at submit before this migration), so they stay '[]' and the
-- UI falls back to reading notes. No backfill — re-parsing that prose
-- is not worth a parser for a handful of rows.
-- ============================================================

ALTER TABLE public.material_request_items
  ADD COLUMN IF NOT EXISTS granite_lines jsonb NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE public.purchase_order_items
  ADD COLUMN IF NOT EXISTS granite_lines jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Dollar-quoted: these comments contain feet/inch marks (10' x 2' 6").
COMMENT ON COLUMN public.material_request_items.granite_lines IS
$c$Area materials (sqft/sqm): the finished pieces the SITE ASKED FOR.
[{id, label, length_in, width_in, count}] — dimensions in INCHES, same
shape as spaces.granite_lines. e.g. [{label:'KitchenTop', length_in:120,
width_in:30, count:4}] = "KitchenTop: 10' x 2' 6" x4" = 100 sq.ft.
requested_qty is the DERIVED sq.ft (graniteSqft()), never stored twice.
Exists so the structured lines round-trip into the editor at PO time
instead of being re-keyed from prose. '[]' for non-area materials.$c$;

COMMENT ON COLUMN public.material_request_items.notes IS
$c$Free-text note. For AREA materials this is the flattened slab summary
generated by graniteSizeNote(), e.g. "KitchenTop: 10' x 2' 6" x4". Kept
denormalised alongside granite_lines so every existing reader shows the
sizes without parsing JSON — and so pre-granite_lines rows still show
what was asked for.$c$;

COMMENT ON COLUMN public.purchase_order_items.granite_lines IS
$c$Area materials (sqft/sqm): the slabs ACTUALLY BOUGHT — vendor stock
rarely matches the request, so these are usually bigger and get cut to
size on site. quantity = graniteSqft(granite_lines) is what the vendor
is paid on. The gap vs the request item's granite_lines is offcut and is
deliberately NOT reconciled away. Captured at PO creation; delivery does
not revise it. '[]' for non-area materials.$c$;

COMMENT ON COLUMN public.purchase_order_items.notes IS
$c$Free-text note. For AREA materials this is the flattened summary of the
slabs actually bought, generated by graniteSizeNote() — same contract as
material_request_items.notes.$c$;
